services:
  - type: web
    name: persona-system
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=1 --threads=2 --worker-class=gthread"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
    autoDeploy: false